name: Scrape Robot Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    # =======================================================
    # VVVV  这就是我们添加的修复代码 VVVV
    permissions:
      contents: write
    # ^^^^  授予工作流写入仓库内容的权限 ^^^^
    # =======================================================

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run scraper
        run: python scripts/scraper.py

      - name: Commit and push if data changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions-bot@github.com'
          git add data/robots.json
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "feat: Auto-update robot data"
            git push
          fi
